apiVersion: v1
kind: Service
metadata:
  name: gui-service
  namespace: hello-kubernetes
spec:
  selector:
    app: gui-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
