apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: front-end-app
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
